const {test,before,after,beforeEach,mock}=require('node:test');
const assert=require('node:assert/strict');const mongoose=require('mongoose');const {MongoMemoryServer}=require('mongodb-memory-server');
process.env.NODE_ENV='test';const notifications=require('../src/services/notification.service');const notified=[];mock.method(notifications,'notify',async(user)=>{notified.push(String(user));return {};});
const User=require('../src/models/User'),Institution=require('../src/models/Institution'),Membership=require('../src/models/StudentInstitutionMembership'),Employment=require('../src/models/TeacherEmployment'),Profile=require('../src/models/StudentProfile'),Link=require('../src/models/ParentChildLink'),Incident=require('../src/models/HealthIncident');
const health=require('../src/controllers/health.controller');let db,owner,student,teacher,parent,sponsor,blocked,outsider,inst,other;
before(async()=>{db=await MongoMemoryServer.create();await mongoose.connect(db.getUri());await Promise.all([User,Institution,Membership,Employment,Profile,Link,Incident].map(m=>m.init()));});after(async()=>{await mongoose.disconnect();await db.stop();});
beforeEach(async()=>{notified.length=0;await Promise.all([User,Institution,Membership,Employment,Profile,Link,Incident].map(m=>m.deleteMany({})));[owner,student,teacher,parent,sponsor,blocked,outsider]=await User.create(['owner','student','teacher','parent','sponsor','blocked','outsider'].map(name=>({fullName:name,email:name+'@health.test',passwordHash:'unused'})));inst=await Institution.create({owner:owner._id,name:'School',slug:'health-school',type:'school',country:'PK'});other=await Institution.create({owner:outsider._id,name:'Other',slug:'health-other',type:'school',country:'PK'});await Membership.create({institution:inst._id,student:student._id,status:'active'});await Employment.create({institution:inst._id,teacher:teacher._id,status:'active',offeredBy:owner._id});await Profile.create({user:student._id,primaryInstitution:other._id});await Link.create([{parent:parent._id,student:student._id,relationship:'father',status:'approved',requestedBy:parent._id,permissions:{viewHealth:true}},{parent:sponsor._id,student:student._id,relationship:'sponsor',status:'approved',requestedBy:sponsor._id,permissions:{viewHealth:true}},{parent:blocked._id,student:student._id,relationship:'mother',status:'approved',requestedBy:blocked._id,permissions:{viewHealth:false}}]);});
function call(fn,user=owner,params={},body={},query={}){return new Promise((resolve,reject)=>{const res={status(){return this;},json(value){resolve(value.data);return this;}};fn({user,params,body,query},res,reject);});}
const create=(user=owner,recipient=student)=>call(health.create,user,{id:inst.id},{student:recipient.id,description:'Fall',severity:'minor'});
test('incident membership is enforced and confidential alerts exclude sponsors and denied guardians',async()=>{await assert.rejects(create(owner,outsider),{statusCode:403});const row=await create();assert.equal(row.parentNotified,true);assert.deepEqual(notified,[parent.id]);await assert.rejects(call(health.child,sponsor,{studentId:student.id}),{statusCode:403});await assert.rejects(call(health.child,blocked,{studentId:student.id}),{statusCode:403});});
test('non-primary institution can edit an active member; static edits are attributed and invalid data rejected',async()=>{await call(health.update,owner,{userId:student.id},{bloodGroup:'o+',vaccinations:[{name:'MMR',date:'2026-01-01'}]},{institution:inst.id});const row=await call(health.record,owner,{userId:student.id},{},{institution:inst.id});assert.equal(row.bloodGroup,'O+');assert.equal(row.healthChanges[0].actor.toString(),owner.id);await assert.rejects(call(health.update,owner,{userId:student.id},{bloodGroup:'invalid'},{institution:inst.id}),{statusCode:422});await assert.rejects(call(health.updateChild,parent,{studentId:student.id},{vaccinations:[{name:''}]}),{statusCode:422});});
test('student and permitted guardian retain incident history across primary-institution changes',async()=>{await create();await Profile.updateOne({user:student._id},{primaryInstitution:null});assert.equal((await call(health.mine,student)).incidents.length,1);assert.equal((await call(health.child,parent,{studentId:student.id})).incidents.length,1);});
test('teacher reports only active students, sees own reports, and cannot read private records or resolve incidents',async()=>{const row=await create(teacher);await assert.rejects(call(health.record,teacher,{userId:student.id},{},{institution:inst.id}),{statusCode:403});await assert.rejects(call(health.followUp,teacher,{incidentId:row.id},{notes:'Done',status:'resolved'}),{statusCode:403});assert.equal((await call(health.teacher,teacher)).incidents.length,1);await assert.rejects(create(outsider),{statusCode:403});});
test('manager acknowledgment and resolution keep follow-up history; notification retry skips already-notified guardians',async()=>{const row=await create();await call(health.followUp,owner,{incidentId:row.id},{status:'acknowledged',notes:'Checked'});const done=await call(health.followUp,owner,{incidentId:row.id},{status:'resolved',notes:'Recovered'});assert.equal(done.followUps.length,2);assert.ok(done.resolvedAt);await call(health.followUp,owner,{incidentId:row.id},{action:'retry_notification'});assert.equal(notified.filter(x=>x===parent.id).length,1);});
test('without eligible guardians, no notification is claimed; a newly permitted guardian can receive retry',async()=>{await Link.updateMany({student:student._id},{'permissions.viewHealth':false});const row=await create();assert.equal(row.parentNotified,false);await Link.updateOne({parent:parent._id},{'permissions.viewHealth':true});const retry=await call(health.followUp,owner,{incidentId:row.id},{action:'retry_notification'});assert.equal(retry.parentNotified,true);assert.deepEqual(notified,[parent.id]);});
