
const {test,before,after,beforeEach,mock}=require('node:test');
const assert=require('node:assert/strict');
const mongoose=require('mongoose');
const {MongoMemoryReplSet}=require('mongodb-memory-server');
process.env.NODE_ENV='test';
const notification=require('../src/services/notification.service');
mock.method(notification,'notifyMany',async()=>[]);mock.method(notification,'notify',async()=>null);
const User=require('../src/models/User'),Institution=require('../src/models/Institution'),Course=require('../src/models/Course'),Lesson=require('../src/models/Lesson'),Enrollment=require('../src/models/Enrollment'),Unit=require('../src/models/LearningUnit'),Version=require('../src/models/ContentVersion'),Activity=require('../src/models/LearningActivity'),Session=require('../src/models/LiveClassSession'),Attendance=require('../src/models/Attendance');
const learning=require('../src/controllers/learning.controller'),legacy=require('../src/controllers/course.controller'),live=require('../src/controllers/liveClass.controller'),tools=require('../src/controllers/liveTools.controller');
let mongo,owner,teacher,student,other,department,principal,institution,course;
before(async()=>{mongo=await MongoMemoryReplSet.create({replSet:{count:1}});await mongoose.connect(mongo.getUri());await Promise.all([Version.init(),Attendance.init()]);});
after(async()=>{await mongoose.disconnect();await mongo.stop();});
beforeEach(async()=>{await Promise.all(Object.values(mongoose.models).map(m=>m.deleteMany({})));[owner,teacher,student,other,department,principal]=await User.create(['Owner','Teacher','Student','Other','Department','Principal'].map((name,i)=>({fullName:name,email:'study'+i+'@test.local',passwordHash:'unused',roles:[i===0?'institution_owner':i===1?'teacher':'student']})));institution=await Institution.create({owner:owner._id,name:'Study Institute',slug:'study-test',type:'university',country:'PK',staff:[{user:department._id,permissions:['content:review:department']},{user:principal._id,permissions:['content:review:principal']}]});course=await Course.create({title:'Study Course',teacher:teacher._id,institution:institution._id,published:true});await Enrollment.create({course:course._id,student:student._id});});
function invoke(handler,user=teacher,body={},params={id:course._id},query={}){return new Promise((resolve,reject)=>{let status=200;const res={status(c){status=c;return this;},json(body){resolve({status,data:body.data});return this;}};Promise.resolve(handler({user,body,params,query},res,reject)).catch(reject);});}
async function makeLesson(body={}){return (await invoke(learning.writeLesson,teacher,{title:'First lesson',...body})).data;}
test('module/chapter hierarchy rejects foreign or mismatched references and deletion of used units',async()=>{const module=(await invoke(learning.createUnit,teacher,{title:'Module',type:'module'})).data;const chapter=(await invoke(learning.createUnit,teacher,{title:'Chapter',type:'chapter',parent:module._id})).data;const lesson=await makeLesson({module:module._id,chapter:chapter._id});assert.equal(String(lesson.chapter),String(chapter._id));await assert.rejects(invoke(learning.writeLesson,teacher,{title:'Wrong',module:module._id,chapter:new mongoose.Types.ObjectId()}),/Chapter/);await assert.rejects(invoke(learning.deleteUnit,teacher,{}, {id:course._id,unitId:module._id}),/Move lessons/);await assert.rejects(invoke(learning.outline,other),/enrollment/);});
test('staged publishing blocks legacy bypasses and supports separate department/principal reviewers',async()=>{await assert.rejects(invoke(learning.policy,teacher,{approvalWorkflow:'staged'}),/managers/);await invoke(learning.policy,owner,{approvalWorkflow:'staged'});const lesson=await makeLesson();assert.equal(lesson.published,false);await invoke(legacy.updateLesson,teacher,{published:true},{lessonId:lesson._id});assert.equal((await Lesson.findById(lesson._id)).published,false);await invoke(legacy.updateCourse,teacher,{published:true});assert.equal((await Course.findById(course._id)).published,false);const ai=(await invoke(legacy.shareAiResource,teacher,{title:'AI draft',content:'Notes'})).data;assert.equal(ai.lesson.published,false);assert.equal(ai.notifiedCount,0);await invoke(learning.review,teacher,{kind:'course',action:'submit'},{itemId:course._id});await assert.rejects(invoke(learning.review,teacher,{kind:'course',action:'approve'},{itemId:course._id}),/reviewer/);await invoke(learning.review,department,{kind:'course',action:'approve'},{itemId:course._id});await invoke(learning.review,principal,{kind:'course',action:'approve'},{itemId:course._id});await invoke(learning.review,teacher,{action:'submit'},{itemId:lesson._id});await invoke(learning.review,department,{action:'approve'},{itemId:lesson._id});await invoke(learning.review,principal,{action:'approve'},{itemId:lesson._id});assert.equal((await Lesson.findById(lesson._id)).published,true);assert.equal((await invoke(learning.outline,student)).data.lessons.length,1);});
test('offline completion is idempotent, refuses changed revisions and dropped enrollment',async()=>{const l=await makeLesson();const body={entries:[{lessonId:l._id,revision:l.revision}]};await invoke(learning.sync,student,body);await invoke(learning.sync,student,body);assert.equal((await Enrollment.findOne({student:student._id})).completedLessons.length,1);await invoke(learning.writeLesson,teacher,{title:'Revised'},{id:course._id,lessonId:l._id});assert.equal((await invoke(learning.sync,student,body)).data[0].status,'blocked');await Enrollment.updateOne({student:student._id},{$set:{status:'dropped'}});await assert.rejects(invoke(learning.packageCourse,student),/enrollment/);assert.equal((await invoke(learning.sync,student,{entries:[{lessonId:l._id,revision:2}]})).data[0].status,'blocked');});
test('version rollback creates a new revision and restore is transactional with foreign references rejected',async()=>{const l=await makeLesson();const backup=(await invoke(learning.backup)).data;await invoke(learning.writeLesson,teacher,{title:'Changed'},{id:course._id,lessonId:l._id});const v=await Version.findOne({item:l._id,revision:1});assert.equal(v.snapshot.title,'First lesson');await invoke(learning.rollback,teacher,{}, {versionId:v._id});assert.equal((await Lesson.findById(l._id)).title,'First lesson');assert.equal((await Lesson.findById(l._id)).revision,3);backup.lessons[0].module=new mongoose.Types.ObjectId();await assert.rejects(invoke(learning.restore,teacher,backup),/module/);assert.equal((await Lesson.findById(l._id)).revision,3);backup.lessons[0].module=null;await invoke(learning.restore,teacher,backup);assert.equal((await Lesson.findById(l._id)).revision,4);});
test('practice activity validates quiz content, lesson ownership and student mutation permissions',async()=>{const l=await makeLesson();await assert.rejects(invoke(learning.activity,teacher,{lesson:l._id,title:'Quiz',type:'quiz',content:{questions:[]}}),/Quiz/);const a=(await invoke(learning.activity,teacher,{lesson:l._id,title:'Quiz',type:'quiz',content:{questions:[{question:'Input?',options:['Keyboard','Monitor'],answer:0}]}})).data;await assert.rejects(invoke(learning.deleteActivity,student,{}, {id:course._id,activityId:a._id}),/permission/);await invoke(learning.deleteActivity,teacher,{}, {id:course._id,activityId:a._id});assert.equal(await Activity.countDocuments(),0);await assert.rejects(makeLesson({resources:[{url:'javascript:alert(1)'}]}),/HTTP/);});
async function liveSession(mode='hybrid'){return Session.create({institution:institution._id,course:course._id,classSection:new mongoose.Types.ObjectId(),teacher:teacher._id,title:'Class',scheduledStart:new Date(),scheduledEnd:new Date(Date.now()+3600000),roomName:'test-'+mode,createdBy:teacher._id,status:'live',startedAt:new Date(),mode});}
test('physical class refuses remote joining; hybrid attendance merges campus and remote students once',async()=>{const physical=await liveSession('physical');await assert.rejects(invoke(live.join,student,{}, {id:physical._id}),/Physical/);await Enrollment.create({course:course._id,student:other._id});const s=await liveSession();await invoke(live.join,student,{}, {id:s._id});await invoke(live.physicalAttendance,teacher,{records:[{student:student._id,status:'absent'},{student:other._id,status:'present'}]},{id:s._id});await invoke(live.end,teacher,{}, {id:s._id});const a=await Attendance.findOne({course:course._id});assert.equal(a.records.length,2);assert.equal(a.records.find(r=>String(r.student)===String(student._id)).status,'present');assert.equal(a.records.find(r=>String(r.student)===String(other._id)).method,'manual');assert.equal((await Enrollment.findOne({student:other._id})).overallScore,100);});
test('classroom permissions, closed quizzes, shared board and unique breakout membership are enforced',async()=>{const s=await liveSession();const params={id:s._id};await assert.rejects(invoke(tools.update,student,{action:'clear'},params),/Teacher/);await assert.rejects(invoke(tools.update,teacher,{action:'closeQuiz'},params),/No quiz/);await invoke(tools.update,student,{action:'board',operation:{type:'text',x:10,y:10,text:'hello'}},params);assert.equal((await invoke(tools.state,teacher,{},params)).data.board.length,1);await assert.rejects(invoke(tools.update,student,{action:'board',operation:{type:'text',x:-1,y:0}},params),/coordinates/);await assert.rejects(invoke(tools.update,teacher,{action:'groups',groups:[{name:'A',students:[student._id]},{name:'A',students:[]}]},params),/unique/);await invoke(tools.update,teacher,{action:'quiz',question:'Q?',options:['A','B'],answer:0},params);let q=(await invoke(tools.state,student,{},params)).data.quiz;assert.equal(q.answer,undefined);await invoke(tools.update,student,{action:'answer',quizId:q.id,answer:0},params);await invoke(tools.update,teacher,{action:'closeQuiz'},params);q=(await invoke(tools.state,student,{},params)).data.quiz;assert.equal(q.answer,0);assert.equal(q.responses,undefined);await assert.rejects(invoke(tools.update,student,{action:'answer',quizId:q.id,answer:1},params),/closed/);});

test('download policy, persisted video position, automatic recovery and analytics are connected',async()=>{const l=await makeLesson();await invoke(learning.policy,owner,{offlineDownloadAllowed:false,copyrightNotice:'Internal teaching',contentLicense:'internal',courseCode:'CS101'});await assert.rejects(invoke(learning.packageCourse,student),/disabled offline/);assert.equal((await Course.findById(course._id)).courseCode,'CS101');await invoke(learning.sync,student,{entries:[{kind:'video',lessonId:l._id,revision:1,seconds:25,duration:100}]});const e=await Enrollment.findOne({student:student._id});assert.equal(e.videoProgress[0].seconds,25);assert.equal(e.completedLessons.length,0);const report=(await invoke(learning.analytics,teacher)).data;assert.equal(report.lessons[0].videoViewers,1);await assert.rejects(invoke(learning.analytics,student),/permission/);const snapshots=(await invoke(learning.backups)).data;assert.ok(snapshots.length>=2);await invoke(learning.writeLesson,teacher,{title:'Changed again'},{id:course._id,lessonId:l._id});await invoke(learning.restoreAutomatic,teacher,{}, {id:course._id,backupId:snapshots[0]._id});assert.equal((await Lesson.findById(l._id)).title,'First lesson');});
test('ending retries do not duplicate attendance and teacher file-sharing policy is enforced',async()=>{const s=await liveSession();const params={id:s._id};await invoke(tools.update,teacher,{action:'policy',policy:{fileSharingAllowed:false,chatAllowed:false}},params);await assert.rejects(invoke(tools.update,student,{action:'file',name:'Notes',url:'https://example.com/notes.pdf'},params),/disabled/);await invoke(live.end,teacher,{},params);await invoke(live.end,teacher,{},params);assert.equal(await Attendance.countDocuments({liveClassSession:s._id}),1);});

test('owner controls reviewer grants while teachers retain metadata editing',async()=>{await invoke(learning.policy,teacher,{courseCode:'IT101',duration:'12 weeks'});assert.equal((await Course.findById(course._id)).courseCode,'IT101');await assert.rejects(invoke(learning.assignReviewer,teacher,{principal:true},{id:course._id,userId:department._id}),/owner/);await invoke(learning.assignReviewer,owner,{principal:true},{id:course._id,userId:department._id});assert.ok((await Institution.findById(institution._id)).staff.find(s=>String(s.user)===String(department._id)).permissions.includes('content:review:principal'));});
test('relay configuration is classroom-scoped and never returns the shared TURN secret',async()=>{const s=await liveSession();process.env.RTC_TURN_URLS='turn:relay.test:3478';process.env.RTC_TURN_SHARED_SECRET='test-shared-secret';try{const config=(await invoke(tools.rtc,student,{}, {id:s._id})).data;assert.equal(config.iceServers.length,2);assert.notEqual(config.iceServers[1].credential,'test-shared-secret');await assert.rejects(invoke(tools.rtc,other,{}, {id:s._id}),/enrollment/);}finally{delete process.env.RTC_TURN_URLS;delete process.env.RTC_TURN_SHARED_SECRET;}});

test('lesson difficulty uses linked graded marks and never invents an ungraded score',async()=>{const Assignment=require('../src/models/Assignment'),Exam=require('../src/models/Exam'),Submission=require('../src/models/Submission'),ExamSubmission=require('../src/models/ExamSubmission');const assignment=await Assignment.create({course:course._id,teacher:teacher._id,title:'Work',maxMarks:100});const exam=await Exam.create({course:course._id,teacher:teacher._id,title:'Test',published:true,questions:[{text:'Q',marks:10}]});const lesson=await makeLesson({assignments:[assignment._id],exams:[exam._id]});await makeLesson({title:'No graded evidence'});await Submission.create({assignment:assignment._id,student:student._id,status:'graded',marksObtained:30});await ExamSubmission.create({exam:exam._id,student:student._id,status:'graded',score:8});const report=(await invoke(learning.analytics)).data;assert.equal(report.averageAssessmentScore,55);assert.equal(report.difficultLessons.length,1);assert.equal(report.difficultLessons[0].averageAssessmentScore,55);assert.equal(report.lessons.find(l=>String(l.lesson)===String(lesson._id)).gradedAttempts,2);assert.equal(report.lessons[1].averageAssessmentScore,null);});

test('content recovery restores linked assessment bodies and simultaneous video positions remain independent',async()=>{const Assignment=require('../src/models/Assignment'),Exam=require('../src/models/Exam');const a=await Assignment.create({course:course._id,teacher:teacher._id,title:'Assignment body',description:'Original task'});const e=await Exam.create({course:course._id,teacher:teacher._id,title:'Exam body',published:true,questions:[{text:'Original question',type:'mcq',options:['A','B'],correctOption:0,marks:10}]});const first=await makeLesson({assignments:[a._id],exams:[e._id]}),second=await makeLesson({title:'Second video'});const backup=(await invoke(learning.backup)).data;await Assignment.deleteOne({_id:a._id});await Exam.deleteOne({_id:e._id});await invoke(learning.restore,teacher,backup);assert.equal((await Assignment.findById(a._id)).description,'Original task');assert.equal((await Exam.findById(e._id)).questions[0].text,'Original question');const lessons=await Lesson.find({course:course._id});await Promise.all(lessons.map(l=>invoke(learning.sync,student,{entries:[{kind:'video',lessonId:l._id,revision:l.revision,seconds:10,duration:60}]})));const enrollment=await Enrollment.findOne({course:course._id,student:student._id});assert.equal(enrollment.videoProgress.length,2);assert.equal(enrollment.completedLessons.length,0);});

test('recalculating old academic work never reactivates a dropped enrollment',async()=>{const l=await makeLesson();await Enrollment.updateOne({course:course._id,student:student._id},{$set:{status:'dropped',completedLessons:[l._id]}});const result=await require('../src/utils/courseProgress').recalculateEnrollmentProgress(student._id,course._id);assert.equal(result,null);assert.equal((await Enrollment.findOne({student:student._id,course:course._id})).status,'dropped');});

test('institution monitors and reviews while only assigned teacher authors curriculum and quizzes',async()=>{const info=(await invoke(learning.outline,owner)).data;assert.equal(info.canManage,true);assert.equal(info.canAuthor,false);assert.equal(info.canSetPolicy,true);assert.equal((await invoke(learning.outline,teacher)).data.canAuthor,true);await invoke(learning.policy,owner,{offlineDownloadAllowed:true});await assert.rejects(invoke(learning.createUnit,owner,{title:'Forbidden module',type:'module'}),/authoring permission/);await assert.rejects(invoke(learning.writeLesson,owner,{title:'Forbidden lesson'}),/authoring permission/);const l=await makeLesson();const body={lesson:l._id,title:'Teacher quiz',type:'quiz',content:{questions:[{question:'Input?',options:['Keyboard','Monitor'],answer:0}]}};await assert.rejects(invoke(learning.activity,owner,body),/authoring permission/);const quiz=(await invoke(learning.activity,teacher,body)).data;await assert.rejects(invoke(learning.updateActivity,owner,body,{id:course._id,activityId:quiz._id}),/authoring permission/);await assert.rejects(invoke(learning.deleteActivity,owner,{}, {id:course._id,activityId:quiz._id}),/authoring permission/);await assert.rejects(invoke(learning.writeLesson,owner,{title:'Changed'},{id:course._id,lessonId:l._id}),/authoring permission/);await invoke(learning.deleteActivity,teacher,{}, {id:course._id,activityId:quiz._id});assert.equal(await Activity.countDocuments(),0);});

test('dual owner and assigned teacher cannot author from institution workspace',async()=>{course.teacher=owner._id;await course.save();assert.equal((await invoke(learning.outline,owner,{}, {id:course._id},{workspace:'institution'})).data.canAuthor,false);assert.equal((await invoke(learning.outline,owner,{}, {id:course._id},{workspace:'teacher'})).data.canAuthor,true);await assert.rejects(invoke(learning.writeLesson,owner,{title:'Forbidden'},{id:course._id},{workspace:'institution'}),/authoring permission/);await invoke(learning.writeLesson,owner,{title:'Teacher workspace lesson'},{id:course._id},{workspace:'teacher'});});
