const router = require('express').Router();

router.use('/auth', require('./auth.routes'));
router.use('/roles', require('./role.routes'));
router.use('/config', require('./config.routes'));
router.use('/institutions', require('./institution.routes'));
router.use('/students', require('./student.routes'));
router.use('/teachers', require('./teacher.routes'));
router.use('/parents', require('./parent.routes'));
router.use('/courses', require('./course.routes'));
router.use('/users', require('./user.routes'));
router.use('/dashboard', require('./dashboard.routes'));
router.use('/messages', require('./message.routes'));
router.use('/notifications', require('./notification.routes'));
router.use('/jobs', require('./job.routes'));
router.use('/job-alerts', require('./jobAlert.routes'));
router.use('/commissions', require('./commission.routes'));
router.use('/inquiries', require('./inquiry.routes'));
router.use('/institution-applications', require('./institutionApplication.routes'));
router.use('/institution-ops', require('./institutionOps.routes'));
router.use('/meetings', require('./meeting.routes'));
router.use('/ptm', require('./ptm.routes'));
router.use('/anonymous-questions', require('./anonymousQuestion.routes'));
router.use('/polls', require('./poll.routes'));
router.use('/newsletters', require('./newsletter.routes'));
router.use('/magazine', require('./magazine.routes'));
router.use('/virtual-fairs', require('./virtualFair.routes'));
router.use('/resumes', require('./resume.routes'));
router.use('/certificates', require('./certificate.routes'));
router.use('/marketplace', require('./marketplace.routes'));
router.use('/scholarships', require('./scholarship.routes'));
router.use('/study-groups', require('./studyGroup.routes'));
router.use('/funding-requests', require('./fundingRequest.routes'));
router.use('/complaints', require('./complaint.routes'));
router.use('/payments', require('./payment.routes'));
router.use('/translate', require('./translate.routes'));
router.use('/ai', require('./ai.routes'));
router.use('/security', require('./security.routes'));
router.use('/webauthn', require('./webauthn.routes'));
router.use('/media', require('./media.routes'));
router.use('/wallet', require('./wallet.routes'));
router.use('/subscriptions', require('./subscription.routes'));
router.use('/teacher-feedback', require('./teacherFeedback.routes'));
router.use('/teacher-employments', require('./teacherEmployment.routes'));
router.use('/employment', require('./employment.routes'));
router.use('/admin', require('./admin.routes'));
router.use('/', require('./cms.routes'));

router.get('/health', (req, res) => res.json({ success: true, message: 'CareerZ API is running.' }));

module.exports = router;
