const Institution = require('../models/Institution');
const feeSchedule = require('../utils/feeSchedule');

let timer = null;
let running = false;

async function runFeeAutomation() {
  if (running) return;
  running = true;
  try {
    const institutionIds = await Institution.find({ verificationStatus: 'approved' }).distinct('_id');
    for (const institutionId of institutionIds) {
      await feeSchedule.autoGenerateDueInvoices(institutionId).catch(() => {});
      await feeSchedule.sweepOverdueAndLateFees(institutionId).catch(() => {});
      await feeSchedule.sweepReminders(institutionId).catch(() => {});
    }
  } finally {
    running = false;
  }
}

function startFeeAutomation() {
  if (timer || process.env.NODE_ENV === 'test') return;
  const intervalMinutes = Math.max(1, Number(process.env.FEE_AUTOMATION_INTERVAL_MINUTES) || 15);
  runFeeAutomation().catch((error) => console.error('[FEE AUTOMATION]', error));
  timer = setInterval(() => runFeeAutomation().catch((error) => console.error('[FEE AUTOMATION]', error)), intervalMinutes * 60 * 1000);
  timer.unref?.();
  console.log(`[SERVER] Fee automation runs every ${intervalMinutes} minute(s).`);
}

module.exports = { startFeeAutomation, runFeeAutomation };
